"""
This type stub file was generated by pyright.
"""

import dataclasses_struct as dcs
from ctypes import LittleEndianStructure
from typing import Annotated, Any, Dict, TypeVar

T = TypeVar('T')

"""Implementation for SMA Speedwire

Originally based on https://github.com/Wired-Square/sma-query/blob/main/src/sma_query_sw/commands.py
Improved with Information from https://github.com/mhop/fhem-mirror/blob/master/fhem/FHEM/76_SMAInverter.pm
Receiver classes completely reimplemented by little.yoda
"""
responseDef: dict[str, list[dict[str, Any]]] = ...
commands: Dict[str, Dict[str, Any]] = ...
#@dcs.dataclass(dcs.BIG_ENDIAN)
class speedwireHeader:
    """Speedwire header"""
    sma: Annotated[bytes, 4]
    tag42_length: dcs.U16
    tag42_tag0x02A0: dcs.U16
    group1: dcs.U32
    smanet2_length: dcs.U16
    smanet2_tagID: dcs.U16
    protokoll: dcs.U16
    def check6065(self) -> bool:
        """Check for 6065 Type, used by inverters. Size is not checked at this stage."""
        ...
    
    def check6069(self) -> bool:
        """Check for 6069 Type, used by energymeters.  Size is not checked at this stage."""
        ...
    
    def __str__(self) -> str:
        """customized output. Use hex-format for important values."""
        ...
    
    def isDiscoveryResponse(self) -> bool:
        """Check if this message is a response to a discovery request."""
        ...

    @classmethod
    def from_packed(cls: type[T], data: bytes) -> T:
        ...
    


#@dcs.dataclass(dcs.BIG_ENDIAN)
class speedwireData2Tag:
    smanet2_lengthPayload: dcs.U16
    smanet2_id: dcs.U16
    protokoll: dcs.U16
    ...

    @classmethod
    def from_packed(cls: type[T], data: bytes) -> T: ...


#@dcs.dataclass(dcs.LITTLE_ENDIAN)
class speedwireHeader6065:
    """Speedwire Header2 for 6065 Messages."""
    unknown09A0E0: Annotated[bytes, 2]
    dest_susyid: dcs.U16
    dest_serial: dcs.U32
    dest_control: dcs.U16
    src_susyid: dcs.U16
    src_serial: dcs.U32
    src_control: dcs.U16
    error: dcs.U16
    fragment: dcs.U16
    pktId: dcs.U16
    cmdid: dcs.U32
    firstRegister: dcs.U32
    lastRegister: dcs.U32
    def isLoginResponse(self) -> bool:
        """Check if this message is a response to a login request."""
        ...
    
    def __str__(self) -> str:
        """customized output. Use hex-format for important values."""
        ...
    
    @classmethod
    def from_packed(cls: type[T], data: bytes) -> T:
        ...


#@dcs.dataclass(dcs.BIG_ENDIAN)
class speedwireHeader6069:
    """Speedwire Header2 for 6069 Messages. 10 Bytes"""
    src_susyid: dcs.U16
    src_serial: dcs.U32
    timestamp: dcs.U32
    ...

    @classmethod
    def from_packed(cls: type[T], data: bytes) -> T:
        ...

#@dcs.dataclass(dcs.LITTLE_ENDIAN)
class speedwireHeader6065x010:
    ...

    @classmethod
    def from_packed(cls: type[T], data: bytes) -> T:
        ...

class SpeedwireFrame:
    """Class for the send speedwire messages"""
    APP_ID = ...
    ANY_SERIAL = ...
    ANY_SUSYID = ...
    LOGIN_TIMEOUT = ...
    def get_encoded_pw(self, password: str, installer: bool = ...) -> bytearray:
        """Encodes the password"""
        ...
    
    _frame_sequence = ...
    _id = ...
    _tag0 = ...
    _group1 = ...
    _eth_sig = ...
    _ctrl2_1 = ...
    _ctrl2_2 = ...
    _data_length = ...
    _longwords = ...
    _ctrl = ...
    class FrameHeader(LittleEndianStructure):
        """Frame Header"""
        _pack_ = ...
        _fields_ = ...
    
    
    class DataHeader(LittleEndianStructure):
        """Data header"""
        _pack_ = ...
        _fields_ = ...
    
    
    class LogoutFrame(LittleEndianStructure):
        """Logout"""
        _pack_ = ...
        _fields_ = ...
    
    
    class LoginFrame(LittleEndianStructure):
        """Login"""
        _pack_ = ...
        _fields_ = ...
    
    
    class QueryFrame(LittleEndianStructure):
        """Query Frame"""
        _pack_ = ...
        _fields_ = ...
    
    
    def getLogoutFrame(self, serial): # -> bytes:
        ...
    
    def getLoginFrame(self, password: str, serial: int, installer: bool) -> bytes:
        """Returns a Login Frame"""
        ...
    
    def getQueryFrame(self, serial: int, command_name: str) -> bytes:
        """Return Query Frame"""
        ...
    
    def getFrameHeader(self) -> FrameHeader:
        """Return Frame Header"""
        ...
    
    def getDataHeader(self, serial: int) -> DataHeader:
        """Return Data Header"""
        ...
    


