"""
This type stub file was generated by pyright.
"""

import attr
from dataclasses import dataclass
from typing import Any, Dict, Iterator, List, Optional, Union

"""Sensor classes for SMA WebConnect library for Python."""
_LOGGER = ...
@dataclass
class Sensor_Range:
    typ: str
    values: list[int]
    editable: bool
    mapper: Dict[int, str] | None = ...
    def __str__(self) -> str:
        """String Function."""
        ...
    
    def names(self) -> Dict[int, str]:
        ...
    


@attr.s(slots=True)
class Sensor:
    """pysma sensor."""
    key: str = ...
    name: str | None = ...
    unit: str | None = ...
    factor: int = ...
    path: Union[list, tuple] = ...
    enabled: bool = ...
    l10n_translate: bool = ...
    value: Any = ...
    key_idx: int = ...
    mapper: dict[int, str] = ...
    mapped_value: Any = ...
    range: Sensor_Range = ...
    webconnect_deviceId: str = ...
    def __attrs_post_init__(self) -> None:
        """Post init Sensor."""
        ...
    
    def extract_value(self, result_body: dict, l10n: Optional[dict] = ...) -> bool:
        """[Webconnect] Extract value from json body.

        Args:
            result_body (dict): json body retrieved from device
            l10n (dict, optional): Dictionary to translate tags to strings. Defaults to None.

        Returns:
            bool: Extracting value successful
        """
        ...
    


class Sensors:
    """SMA Sensors."""
    def __init__(self, sensors: Union[Sensor, List[Sensor], None] = ...) -> None:
        """Init Sensors.

        Args:
            sensors (Union[Sensor, List[Sensor], None], optional): One or a list of sensors
                to add on init. Defaults to None.
        """
        ...
    
    def __len__(self) -> int:
        """Length of Sensor list.

        Returns:
            int: Number of Sensor objects
        """
        ...
    
    def __contains__(self, key: Sensor | str) -> bool:
        """Check if a sensor is defined.

        Args:
            key (str, Sensor): [description]

        Returns:
            bool: [description]
        """
        ...
    
    def __getitem__(self, key: str) -> Sensor:
        """Get a sensor.

        Args:
            key (str): Either the name or key of the Sensor

        Raises:
            KeyError: Item was not found

        Returns:
            Sensor: The matching Sensor object
        """
        ...
    
    def __iter__(self) -> Iterator[Sensor]:
        """Iterate Sensor objects.

        Yields:
            Iterator[Sensor]: Sensor iterator
        """
        ...
    
    def add(self, sensor: Union[Sensor, List[Sensor]]) -> None:
        """Add a sensor, logs warning if it exists.

        A copy of sensor, or the sensors in the list, will be added.
        If the sensor name already exists it will be overwritten.
        If the sensor key already exists it will not be added.

        Args:
            sensor (Sensor, List[Sensor]): One or a list of sensors to add

        Raises:
            TypeError: Argument sensor does not match an expected type
        """
        ...
    
    def __str__(self) -> str:
        """Return the dict as string."""
        ...
    


